### ISSUE TITLE
filter_less_than_nationality не работает

### ISSUE THREAD

**Issue by AlphaBeth** [pravlev/lab5#5]
```
filter_less_than_nationality        
No such command. Type "help" to get all commands with their names and descriptions
filter_less_than_nationality SPAIN
Command with wrong argument. Type "help" to get all commands with their name and description
filter_less_than_nationality 1
Command with wrong argument. Type "help" to get all commands with their name and description
filter_less_than_nationality INDIA
Command with wrong argument. Type "help" to get all commands with their name and description
```

**Comment by AlphaBeth** [comment]
Ещё и опечатка в help

**Comment by AlphaBeth** [comment]
```
filter_less_than_nationality
Enter nationality(UNITED_KINGDOM,GERMANY,SPAIN,INDIA,THAILAND): SPAIN
Exception in thread "main" java.lang.NullPointerException
        at com.lev_prav.client.utility.CollectionManager.lambda$filerLessThanNationality$0(CollectionManager.java:120)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at java.util.ArrayDeque$DeqSpliterator.forEachRemaining(ArrayDeque.java:951)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.lev_prav.client.utility.CollectionManager.filerLessThanNationality(CollectionManager.java:120)
        at com.lev_prav.client.commands.FilterLessThanNationalityCommand.execute(FilterLessThanNationalityCommand.java:27)
        at com.lev_prav.client.utility.ConsoleManager.start(ConsoleManager.java:37)
        at com.lev_prav.client.Client.main(Client.java:30)
```

**Comment by AlphaBeth** [comment]
Аргумент должен передаваться сразу с командой, а не читаться отдельно.
