### ISSUE TITLE
Ошибка при вводе ctrl+d

### ISSUE THREAD

**Issue by AlphaBeth** [pravlev/lab5#8]

**Comment by AlphaBeth** [comment]
```
Picked up _JAVA_OPTIONS: -Xmx128M -Xms128M
Exception in thread "main" java.util.NoSuchElementException: No line found
        at java.util.Scanner.nextLine(Scanner.java:1540)
        at com.lev_prav.client.userio.UserIO.readline(UserIO.java:42)
        at com.lev_prav.client.utility.ConsoleManager.start(ConsoleManager.java:27)
        at com.lev_prav.client.Client.main(Client.java:30)
```
